# Generated by Django 4.2.1 on 2023-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="thumbnail",
            field=models.FileField(upload_to="movie_thumbnails"),
        ),
    ]
