# Generated by Django 4.2.1 on 2023-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_movie_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(null=True, to="main.genre"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="thumbnail",
            field=models.FileField(null=True, upload_to="movie_thumbnails"),
        ),
    ]
