# Generated by Django 4.2.1 on 2023-05-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_movie_genres_alter_movie_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
