# Generated by Django 4.2.1 on 2023-05-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_movie_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="thumbnail",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
